///|
typealias LLVMContext = @IR.LLVMContext

///|
traitalias Type = @IR.Type

/////|
//typealias HalfType = @IR.HalfType
//
/////|
//typealias BFloatType = @IR.BFloatType
//
/////|
//typealias FloatType = @IR.FloatType
//
/////|
//typealias DoubleType = @IR.DoubleType
//
/////|
//typealias IntegerType = @IR.IntegerType
//
/////|
//typealias X86_FP80Type = @IR.X86_FP80Type
//
/////|
//typealias PPC_FP128Type = @IR.PPC_FP128Type
//
/////|
//typealias VoidType = @IR.VoidType
//
/////|
//typealias LabelType = @IR.LabelType
//
/////|
//typealias MetadataType = @IR.MetadataType
//
/////|
//typealias TokenType = @IR.TokenType
//
/////|
//typealias X86_AMXType = @IR.X86_AMXType
//
///|
//typealias FunctionType = @IR.FunctionType
